collections:
  posts:
    output: true
    permalink: /:collection/:name
  news-items:
    output: true

# defaults:
#   - scope:
#       path: ""
#       type: "posts"
#     values:
#       layout: "post"

gems:
  - jekyll-archives
  - jekyll-seo-tag

jekyll-archives:
  enabled: 'all'
  layout: 'post-list'
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
