collections:
  posts:
    output: true
    permalink: /:collection/:name

gems:
  - jekyll-archives
  - jekyll-seo-tag

jekyll-archives:
  enabled: 'all'
  layout: 'post-list'
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
