collections:
  example:
    output: true

gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tags

jekyll-archives:
  enabled: 'all'
  layout: 'post-list'
  permalinks:
    year: '/archives/year/:year/'
    month: '/archives/month/:year-:month/'
    tag: '/archives/tag/:name/'
